CREATE
EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS repo;

--------------------------------------------------------------------------------------------------------
CREATE TABLE auth.users
(
    user_id         UUID                     NOT NULL,

    github_id       BIGINT                   NOT NULL,
    github_username VARCHAR(100)             NOT NULL,
    display_name    VARCHAR(200)             NOT NULL,
    avatar_url      VARCHAR(500),
    access_token    TEXT                     NOT NULL,
    token_scopes    VARCHAR(500),

    version         BIGINT                   NOT NULL DEFAULT 0,

    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by      UUID,
    updated_by      UUID,

    CONSTRAINT pk_users
        PRIMARY KEY (user_id),

    CONSTRAINT uk_users_github_id
        UNIQUE (github_id),

    CONSTRAINT uk_users_github_username
        UNIQUE (github_username)
);

CREATE INDEX idx_users_github_id
    ON auth.users (github_id);

CREATE INDEX idx_users_github_username
    ON auth.users (github_username);

--------------------------------------------------------------------------------------------------------
CREATE TABLE auth.refresh_tokens
(
    refresh_token_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    jti               VARCHAR(128)             NOT NULL,
    user_id           UUID                     NOT NULL,

    expires_at        TIMESTAMP WITH TIME ZONE NOT NULL,

    revoked           BOOLEAN                  NOT NULL DEFAULT FALSE,

    replaced_by_token VARCHAR(128),

    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,

    created_by        UUID,
    updated_by        UUID,

    version           BIGINT                   NOT NULL DEFAULT 0,

    CONSTRAINT uk_refresh_token_jti
        UNIQUE (jti),

    CONSTRAINT fk_refresh_token_user
        FOREIGN KEY (user_id)
            REFERENCES auth.users (user_id)
            ON DELETE CASCADE
);

CREATE INDEX idx_refresh_token_user
    ON auth.refresh_tokens (user_id);

CREATE INDEX idx_refresh_token_expires_at
    ON auth.refresh_tokens (expires_at);

CREATE INDEX idx_refresh_token_revoked_expires
    ON auth.refresh_tokens (revoked, expires_at);

--------------------------------------------------------------------------------------------------------
CREATE TABLE auth.roles
(
    role_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name        VARCHAR(255)             NOT NULL,
    role_description VARCHAR(500),

    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,

    created_by       UUID,
    updated_by       UUID,

    version          BIGINT                   NOT NULL DEFAULT 0,

    CONSTRAINT uk_role
        UNIQUE (role_name)
);

CREATE INDEX idx_role
    ON auth.roles (role_name);

--------------------------------------------------------------------------------------------------------
CREATE TABLE auth.user_roles
(
    user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id      UUID                     NOT NULL,
    role_id      BIGINT                   NOT NULL,

    status       VARCHAR(20)              NOT NULL DEFAULT 'ACTIVE',

    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,

    created_by   UUID,
    updated_by   UUID,

    version      BIGINT                   NOT NULL DEFAULT 0,

    CONSTRAINT fk_user_role_user
        FOREIGN KEY (user_id)
            REFERENCES auth.users (user_id)
            ON DELETE CASCADE,

    CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id)
            REFERENCES auth.roles (role_id)
            ON DELETE CASCADE,

    CONSTRAINT uk_user_role
        UNIQUE (user_id, role_id),

    CONSTRAINT chk_user_role_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_user_role_user
    ON auth.user_roles (user_id);

CREATE INDEX idx_user_role_role
    ON auth.user_roles (role_id);

--------------------------------------------------------------------------------------------------------
CREATE TABLE repo.repositories
(
    repository_id   UUID                     NOT NULL,

    user_id         UUID                     NOT NULL,
    github_repo_id  BIGINT                   NOT NULL,

    owner           VARCHAR(100)             NOT NULL,
    name            VARCHAR(200)             NOT NULL,
    full_name       VARCHAR(300)             NOT NULL,

    is_private      BOOLEAN                  NOT NULL DEFAULT FALSE,
    default_branch  VARCHAR(100)             NOT NULL DEFAULT 'main',

    language        VARCHAR(100),
    html_url        VARCHAR(500),
    description     TEXT,

    index_status    VARCHAR(20)              NOT NULL DEFAULT 'PENDING',

    indexed_at      TIMESTAMP WITH TIME ZONE,

    chunk_count     INTEGER                  NOT NULL DEFAULT 0,
    files_total     INTEGER                  NOT NULL DEFAULT 0,
    files_processed INTEGER                  NOT NULL DEFAULT 0,

    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,

    created_by      UUID,
    updated_by      UUID,

    version         BIGINT                   NOT NULL DEFAULT 0,

    CONSTRAINT uk_repositories_user_github_repo
        UNIQUE (user_id, github_repo_id),

    CONSTRAINT chk_repositories_index_status
        CHECK (
            index_status IN (
                             'PENDING',
                             'INDEXING',
                             'INDEXED',
                             'FAILED'
                )
            ),
    CONSTRAINT pk_users
        PRIMARY KEY (repository_id)
);

CREATE INDEX idx_repositories_user_id
    ON repo.repositories (user_id);

CREATE INDEX idx_repositories_index_status
    ON repo.repositories (index_status);